import { useMemo, useState } from "react";
import { ArrowUpRight, Banknote, Bot, CircleDollarSign, Gauge, Plus, WalletCards } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { StatCard } from "../components/StatCard";
import { demoBusiness, demoTransactions, monthly } from "../data/demo";
import { askAdvisor } from "../services/ai";
import type { Transaction } from "../types";

export function Dashboard({page,setPage}:{page:string;setPage:(p:string)=>void}) {
 const [transactions,setTransactions]=useState<Transaction[]>(demoTransactions); const [message,setMessage]=useState(""); const [answer,setAnswer]=useState("Your revenue is growing faster than expenses. Review transport and raw-material costs to protect your margin."); const [sending,setSending]=useState(false);
 const totals=useMemo(()=>transactions.reduce((a,t)=>{t.type==="income"?a.income+=t.amount:a.expense+=t.amount;return a},{income:0,expense:0}),[transactions]);
 const profit=totals.income-totals.expense;
 if(page==="advisor") return <Advisor message={message} setMessage={setMessage} answer={answer} setAnswer={setAnswer} sending={sending} setSending={setSending}/>;
 if(page==="financials") return <Financials transactions={transactions} setTransactions={setTransactions}/>;
 if(page==="market") return <Market/>;
 if(page==="plan") return <Plan/>;
 if(page==="funding") return <Funding/>;
 if(page==="reports") return <Reports/>;
 if(page==="business") return <Business/>;
 return <div className="reveal space-y-6">
   <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-zinc-500">Saturday, September 5, 2026</p><h1 className="mt-1 text-3xl font-bold">Welcome back, Maya</h1><p className="mt-2 text-zinc-500">Here is your business snapshot.</p></div><Button onClick={()=>setPage("financials")}><Plus size={17}/> Add transaction</Button></div>
   <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Health Score" value="76/100" change="+4.2%" icon={<Gauge size={18}/>}/><StatCard label="Revenue" value={`₹${(totals.income/1000).toFixed(1)}K`} change="+8.6%" icon={<Banknote size={18}/>}/><StatCard label="Expenses" value={`₹${(totals.expense/1000).toFixed(1)}K`} icon={<WalletCards size={18}/>}/><StatCard label="Est. Profit" value={`₹${(profit/1000).toFixed(1)}K`} change="+12.4%" icon={<CircleDollarSign size={18}/>}/><StatCard label="Cash Flow" value="Healthy" change="+6.1%" icon={<ArrowUpRight size={18}/>}/></div>
   <div className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Revenue vs Expenses</h2><p className="mt-1 text-xs text-zinc-500">Last 5 months · demo snapshot</p></div><span className="rounded-full bg-lime/10 px-2 py-1 text-xs text-lime">Growing</span></div><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthly}><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="month" stroke="#666" tickLine={false} axisLine={false}/><YAxis stroke="#666" tickLine={false} axisLine={false} width={40}/><Tooltip contentStyle={{background:"#0d110e",border:"1px solid rgba(255,255,255,.1)",borderRadius:12}}/><Line type="monotone" dataKey="income" stroke="#b7f34a" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="expense" stroke="#8b9288" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></Card>
   <Card><div className="flex items-center gap-2 text-lime"><Bot size={19}/><h2 className="font-semibold text-white">AI INSIGHTS</h2></div><p className="mt-4 text-sm leading-7 text-zinc-300">{answer}</p><button onClick={()=>setPage("advisor")} className="mt-6 text-sm font-semibold text-lime">Ask BIZNEX Advisor →</button><div className="mt-7 border-t border-white/[.06] pt-5"><p className="text-xs text-zinc-500">LOCAL BUSINESS OPPORTUNITY</p><div className="mt-2 text-4xl font-black">78<span className="text-lg text-zinc-500">/100</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><span className="rounded-lg bg-white/[.03] p-2">Demand<br/><b className="text-lime">High</b></span><span className="rounded-lg bg-white/[.03] p-2">Competition<br/><b>Medium</b></span><span className="rounded-lg bg-white/[.03] p-2">Growth<br/><b className="text-lime">High</b></span></div></div></Card></div>
 </div>
}

function Advisor({message,setMessage,answer,setAnswer,sending,setSending}:{message:string;setMessage:(v:string)=>void;answer:string;setAnswer:(v:string)=>void;sending:boolean;setSending:(v:boolean)=>void}) {
 async function send(){if(!message.trim())return;setSending(true);const a=await askAdvisor(message,demoBusiness);setAnswer(a);setMessage("");setSending(false)}
 const suggestions=["How can I increase my profit?","How much money do I need to start?","What are my biggest expenses?","Should I take a loan?"];
 return <div className="reveal grid gap-4 xl:grid-cols-[240px_1fr]"><Card className="hidden xl:block"><p className="text-xs uppercase tracking-wider text-zinc-500">Conversations</p><div className="mt-5 space-y-2"><div className="rounded-xl bg-lime/10 p-3 text-sm text-lime">Business growth review</div><div className="p-3 text-sm text-zinc-500">Monthly finances</div></div></Card><Card className="min-h-[620px]"><div className="flex items-center gap-3 border-b border-white/[.06] pb-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-lime/10 text-lime"><Bot/></div><div><h1 className="font-bold">BIZNEX Advisor</h1><p className="text-xs text-zinc-500">Context-aware guidance · Demo mode</p></div></div><div className="mx-auto flex max-w-3xl flex-col gap-4 py-7"><div className="rounded-2xl bg-white/[.03] p-4 text-sm leading-7 text-zinc-300"><b className="text-white">BIZNEX Advisor</b><br/>Hello! I'm your BIZNEX Business Advisor. Tell me what you're planning, and I'll help you make a practical business decision.</div><div className="rounded-2xl border border-lime/15 bg-lime/5 p-4 text-sm leading-7 text-zinc-300"><b className="text-lime">Recommendation</b><br/>{answer}<div className="mt-3 text-xs text-zinc-500">Guidance only — outcomes are not guaranteed.</div></div><div className="flex flex-wrap gap-2">{suggestions.map(s=><button key={s} onClick={()=>setMessage(s)} className="rounded-full border border-white/10 px-3 py-2 text-xs text-zinc-400 hover:border-lime/30 hover:text-white">{s}</button>)}</div><div className="mt-auto flex gap-2 rounded-2xl border border-white/10 bg-white/[.025] p-2"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} className="flex-1 bg-transparent px-3 py-3 text-sm outline-none" placeholder="Ask about your business…"/><Button onClick={send} disabled={sending}>{sending?"Thinking…":"Send"}</Button></div></div></Card></div>
}

function Financials({transactions,setTransactions}:{transactions:Transaction[];setTransactions:React.Dispatch<React.SetStateAction<Transaction[]>>}) {
 const [type,setType]=useState<"income"|"expense">("income");const [amount,setAmount]=useState("");const [desc,setDesc]=useState("");
 function add(){const n=Number(amount);if(!n)return;setTransactions(t=>[{id:crypto.randomUUID(),type,category:type==="income"?"Sales":"Other",amount:n,date:new Date().toISOString().slice(0,10),description:desc||"Manual entry"},...t]);setAmount("");setDesc("")}
 const income=transactions.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),expense=transactions.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0);
 return <div className="reveal space-y-5"><div><h1 className="text-3xl font-bold">Financials</h1><p className="mt-2 text-zinc-500">Track money in, money out and the story behind your cash flow.</p></div><div className="grid gap-3 sm:grid-cols-3"><StatCard label="Total Income" value={`₹${income.toLocaleString()}`} icon={<Banknote/>}/><StatCard label="Total Expenses" value={`₹${expense.toLocaleString()}`} icon={<WalletCards/>}/><StatCard label="Net Profit" value={`₹${(income-expense).toLocaleString()}`} icon={<CircleDollarSign/>}/></div><Card><h2 className="font-semibold">Add transaction</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><select value={type} onChange={e=>setType(e.target.value as "income"|"expense")} className="rounded-xl border border-white/10 bg-[#0d110e] px-3 py-3 text-sm"><option value="income">Income</option><option value="expense">Expense</option></select><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount (₹)" className="rounded-xl border border-white/10 bg-white/[.025] px-3 py-3 text-sm outline-none"/><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Description" className="rounded-xl border border-white/10 bg-white/[.025] px-3 py-3 text-sm outline-none"/><Button onClick={add}>Add transaction</Button></div></Card><Card><div className="flex items-center justify-between"><h2 className="font-semibold">Recent transactions</h2><span className="text-xs text-zinc-600">{transactions.length} entries</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="text-xs text-zinc-600"><tr><th className="py-3">Date</th><th>Type</th><th>Description</th><th>Category</th><th className="text-right">Amount</th></tr></thead><tbody>{transactions.map(t=><tr className="border-t border-white/[.05]" key={t.id}><td className="py-3 text-zinc-500">{t.date}</td><td><span className={t.type==="income"?"text-lime":"text-zinc-400"}>{t.type}</span></td><td>{t.description}</td><td className="text-zinc-500">{t.category}</td><td className="text-right font-semibold">₹{t.amount.toLocaleString()}</td></tr>)}</tbody></table></div></Card></div>
}

function Market(){return <div className="reveal space-y-5"><div><h1 className="text-3xl font-bold">Local Market Insights</h1><p className="mt-2 text-zinc-500">Demo estimates are clearly marked until verified local data sources are connected.</p></div><Card><div className="grid gap-3 md:grid-cols-3"><input defaultValue="Malda, West Bengal" className="rounded-xl border border-white/10 bg-white/[.025] px-3 py-3 text-sm"/><input defaultValue="Food & Processing" className="rounded-xl border border-white/10 bg-white/[.025] px-3 py-3 text-sm"/><input placeholder="Product / service" className="rounded-xl border border-white/10 bg-white/[.025] px-3 py-3 text-sm"/></div><div className="mt-7 grid gap-4 md:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl bg-lime/5 p-7 text-center"><p className="text-xs tracking-wider text-zinc-500">DEMO ESTIMATE</p><div className="mt-3 text-6xl font-black text-gradient">78</div><p className="mt-1 text-zinc-500">Local opportunity / 100</p></div><div className="grid gap-3 sm:grid-cols-3">{[["Demand","High"],["Competition","Medium"],["Growth","High"]].map(([a,b])=><div key={a} className="rounded-xl border border-white/[.07] p-4"><p className="text-xs text-zinc-500">{a}</p><p className="mt-2 font-bold text-lime">{b}</p></div>)}</div></div><div className="mt-4 rounded-xl border border-amber-400/10 bg-amber-400/5 p-4 text-xs leading-6 text-amber-200/70">This is a prototype estimate, not verified market data. Connect a trusted location/market data provider before presenting it as factual.</div></Card></div>}
function Plan(){const [generated,setGenerated]=useState(false);return <div className="reveal space-y-5"><div><h1 className="text-3xl font-bold">Business Plan Generator</h1><p className="mt-2 text-zinc-500">Turn your idea into a structured, editable plan.</p></div><Card><div className="grid gap-3 md:grid-cols-2"><textarea placeholder="Business idea" className="min-h-28 rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm outline-none"/><textarea placeholder="Target customers" className="min-h-28 rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm outline-none"/><input placeholder="Estimated investment (₹)" className="rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm"/><input placeholder="Expected monthly revenue (₹)" className="rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm"/></div><Button className="mt-4" onClick={()=>setGenerated(true)}>{generated?"Regenerate plan":"Generate business plan"}</Button></Card>{generated&&<Card><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Maya Foods — Business Plan</h2><span className="rounded-full bg-lime/10 px-3 py-1 text-xs text-lime">Demo generated</span></div>{["Executive Summary","Business Description","Target Customers","Local Market Overview","Products & Services","Pricing Strategy","Marketing Strategy","Operations Plan","Financial Projection","Risks & Growth Strategy"].map((s,i)=><div className="mt-6 border-t border-white/[.06] pt-5" key={s}><h3 className="font-semibold">{i+1}. {s}</h3><p className="mt-2 text-sm leading-7 text-zinc-400">Build this section around the entrepreneur's local context, current financial picture and growth goal. Connect the secure AI function to generate personalized content when an AI provider is configured.</p></div>)}</Card>}</div>}
function Funding(){return <div className="reveal space-y-5"><div><h1 className="text-3xl font-bold">Funding Assistant</h1><p className="mt-2 text-zinc-500">Illustrative planning support — not a loan approval or guarantee.</p></div><Card><div className="grid gap-3 md:grid-cols-3"><input placeholder="Required funding (₹)" className="rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm"/><input placeholder="Purpose" className="rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm"/><input placeholder="Current revenue (₹)" className="rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm"/></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-xl bg-white/[.03] p-5"><p className="text-xs text-zinc-500">Potential range</p><p className="mt-2 text-2xl font-bold">₹50K–₹1.5L</p></div><div className="rounded-xl bg-white/[.03] p-5"><p className="text-xs text-zinc-500">Planning status</p><p className="mt-2 text-2xl font-bold text-lime">Potentially suitable</p></div><div className="rounded-xl bg-white/[.03] p-5"><p className="text-xs text-zinc-500">Repayment</p><p className="mt-2 text-2xl font-bold">Illustrative</p></div></div><p className="mt-5 text-xs leading-6 text-zinc-600">Check eligibility, rates and terms directly with the official lender or government scheme before making a decision.</p></Card></div>}
function Reports(){return <div className="reveal space-y-5"><div><h1 className="text-3xl font-bold">Reports</h1><p className="mt-2 text-zinc-500">Downloadable report architecture is ready for secure server-side generation.</p></div><div className="grid gap-3 md:grid-cols-2">{["Monthly Financial Report","Business Health Report","Income / Expense Report","AI Business Recommendations","Business Plan"].map(x=><Card key={x}><div className="flex items-center justify-between"><div><h3 className="font-semibold">{x}</h3><p className="mt-1 text-xs text-zinc-600">Ready for demo export</p></div><Button variant="secondary" onClick={()=>alert("Demo export: connect a PDF generator in production.")}>Download</Button></div></Card>)}</div></div>}
function Business(){return <div className="reveal space-y-5"><div><h1 className="text-3xl font-bold">My Business</h1><p className="mt-2 text-zinc-500">Your core business profile and health signals.</p></div><Card><div className="grid gap-5 md:grid-cols-2"><div><p className="text-xs text-zinc-500">Business name</p><p className="mt-1 text-xl font-bold">{demoBusiness.name}</p></div><div><p className="text-xs text-zinc-500">Category</p><p className="mt-1">{demoBusiness.category}</p></div><div><p className="text-xs text-zinc-500">Location</p><p className="mt-1">{demoBusiness.location}</p></div><div><p className="text-xs text-zinc-500">Primary goal</p><p className="mt-1 text-lime">{demoBusiness.goal}</p></div></div></Card><Card><h2 className="font-semibold">Business Health Score</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Profitability",82],["Cash Flow",71],["Expense Control",68],["Growth",80],["Financial Stability",75]].map(([x,n])=><div key={String(x)} className="rounded-xl bg-white/[.03] p-4"><p className="text-xs text-zinc-500">{x}</p><p className="mt-2 text-2xl font-bold">{n}</p><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-lime" style={{width:`${n}%`}}/></div></div>)}</div></Card></div>}
